### ISSUE TITLE
What do you think of the latex suite plugin

### ISSUE THREAD

**Issue by windily-cloud** [rabirabirara/obsidian-jelly-snippets#1]
There is a awesome plugin called [latex suite](https://github.com/artisticat1/obsidian-latex-suite), which is updated very frequently. It supports custom snippets, auto-completion, tab-completion, cursor-jumping, regular-completion and many other features. I find it fits your needs very well, or maybe I didn't fully understand your needs, you can take a look at this plugin

I'd love to see a lot of plugins in the community, but it seems like a lot of people building a plugin together would make it even more powerful.

**Comment by rabirabirara** [comment]
Wow, it is an extremely powerful plugin! Very cool work. It's far better than mine. I actually did not know about this plugin before writing. 😅 If I had, I would've been too discouraged to write anything.

Sure, if the goal was just to fit my needs, I'd use the plugin and call it a day. In fact, just using my own repository would be sufficient; I wouldn't need to publish it. 

But that wasn't the goal here; the goal was to make something dead simple and on my own. That is why I am still intent on improving the plugin for maintainers' satisfaction. You might say that I didn't think about other people writing this; that is a valid criticism. You might say that with the existence of the other plugin, mine is obsolete. That's fair.

That does not matter to me, however. This plugin is extremely young (and to be honest, I also wanted to publish it just so that I could use it on my other devices without using git) and it could go anywhere from here. I could also just transform the plugin to *specifically* outline my notetaking syntax, so that it would have some kind of specific use, but I kept it general.

If the maintainers see a problem with my plugin being published and opine to keep it unpublished, even for a reason like "simplicity in the plugin store" or "aesthetics", then I will accept it. Until then, I won't withdraw this. Liam Cain notes that multiple plugins serving the same purpose is a nonissue ([Unofficial API FAQ](https://liamca.in/Obsidian/Plugin+Review+Guide/index#Competition)) (though I'd hardly say my plugin is in "competition" with that lovely beast!).

I don't think I'd have anything to contribute to Latex Suite; it's pretty complete and has a large userbase. Someone will always be down to fix the bugs. But if I'm just doing small stuff, I'd rather do small things for projects I personally enjoy in other communities.

Most importantly, I want to thank you for visiting the repository and offering your thoughts. This is pretty much my first real open-source project. I'm treasuring and internalizing every bit of feedback I receive. Next time I'll have better ideas!

**Comment by windily-cloud** [comment]
Thank you for your reply, I understand it now. My initial thought was if there was a better plugin that could save you time. If I have offended in any way, you please say so and I will accept it.

Don't take it to heart, I'm very supportive of your work, the community is more diverse with you guys, and everyone has their own design philosophy. Or simple, or elegant, or convenient. I will continue to follow you, thank you very much for your selfless dedication!

**Comment by rabirabirara** [comment]
Thank you for your kind words! I feel encouraged to write another plugin because of you. :)
