### ISSUE TITLE
[FR] Trigger on Enter

### ISSUE THREAD

**Issue by AaronKnowls** [rabirabirara/obsidian-jelly-snippets#3]
Loving your plugin so far, I've switch from Text Snippets.

I'd love to have the option to trigger on enter, although I'm aware this might have some issues I'm not aware of since the Text Snippets plugin doesn't have it either, or maybe it's just not that useful for that many people.

In any case, just for your consideration, since it would great in my workflow to have that option.

Thank you for your work!

**Comment by rabirabirara** [comment]
I was also thinking about adding this. That is literally the most useful key to have snippets trigger on.

From an immediate perspective, pressing Enter in Obsidian seems to register the newline first before triggering the snippet; this wasn't the case with Space or Tab, which is why those keys worked. I'll give it a serious thought when I'm less busy with schoolwork!

**Comment by rabirabirara** [comment]
Ok, update your plugin. There should be an option for this now. It should also work better than before, in a sense.

**Comment by rabirabirara** [comment]
Actually, DON'T update your plugin. Found a terrible bug... I really should have tests.

**Comment by rabirabirara** [comment]
Okay... it should work correctly now... hopefully... I need to pay attention to my coding practices.
