### ISSUE TITLE
Clarify how to write snippts, maybe consider making the syntax simpler.

### ISSUE THREAD

**Issue by YousufSSyed** [rabirabirara/obsidian-jelly-snippets#4]
I looked at the "What does it do" section but its pretty confusing how I'm supposed to use it. If you know plugins like Text Snippets exist, then why the syntax for this plugin more complicated? I think that would be a huge barrier for users to use this.

**Comment by rabirabirara** [comment]
Thanks for the feedback. I will write a clearer introduction to snippet writing.

The reason why the syntax has both a snippet divider (e.g. -==-) and a snippet *part* divider (e.g. |+|) is so that we allow for snippets with multiple lines. Text Snippets only has snippets per line. 

![image](https://user-images.githubusercontent.com/59306451/231574205-d7702439-b0ec-48f1-b06b-5e3e54fedb92.png)

The syntax is very simple but, and I suppose this is me personally, I never felt secure that something wouldn't go wrong in my snippets on accident. I'd rather a user define a completely impossible divider from the start and see it all over their syntax file, so they don't have to change it later when they need the symbol (by default, the colon ':' which I use very often).

I was definitely a little lazy writing the current readme!

**Comment by rabirabirara** [comment]
Updated the readme. Am thinking about making an option in settings to have only newlines be the snippet divider. That is, to give the option to have a custom snippet divider but use newlines by default. Seems like it would help. The defaults should definitely be simpler, that's a great point.
